name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 依存関係をインストール
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black でフォーマットチェック
        run: |
          cd backend
          source venv/bin/activate
          black --check .

      - name: Pytest でテスト実行
        run: |
          cd backend
          source venv/bin/activate
          pytest