name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 依存関係をインストール
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: インスタンスディレクトリを作成
        run: |
          mkdir -p backend/app/instance
          touch backend/app/instance/database.db  # SQLite用のデータベースファイルを作成

      - name: 環境変数を設定
        run: |
          echo "FLASK_APP=app" >> $GITHUB_ENV
          echo "PYTHONPATH=$PWD/backend" >> $GITHUB_ENV

      - name: データベースマイグレーションを実行
        run: |
          cd backend
          source venv/bin/activate
          flask db init || true  
          flask db migrate -m "initial migration" || true
          flask db upgrade
          flask db current  

      - name: Black でフォーマットチェック
        run: |
          cd backend
          source venv/bin/activate
          black --check .

      - name: Pytest でテスト実行
        run: |
          cd backend
          source venv/bin/activate
          export FLASK_APP=app
          export FLASK_ENV=testing
          export PYTHONPATH=$(pwd)
          flask db upgrade  
          pytest
